Areas/Admin/Controllers/AdminRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EcommerceWeb.Models;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace EcommerceWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminRoleController : Controller
    {
        private readonly dbEcommerceContext _context;
        private INotyfService _notifyService { get; }    

        public AdminRoleController(dbEcommerceContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: AdminRole
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: AdminRole/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: AdminRole/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminRole/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                _notifyService.Success("Create new success");
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: AdminRole/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: AdminRole/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,Description")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                    _notifyService.Success("Update Success");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        _notifyService.Warning("Error");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: AdminRole/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: AdminRole/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            _notifyService.Success("Delete Success");
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.RoleId == id);
        }
    }
}

Areas/Admin/Views/AdminRole/Create.cshtml
@model EcommerceWeb.Models.Role

@{
    ViewData["Title"] = "Create Role    ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminRole" asp-action="Index" class="breadcrumb-item">Manage role</a>
            <span class="breadcrumb-item active">Create new role</span>
        </nav>
    </div>
</div>

<div>
    <h1>Create new role</h1>

    <form asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group col-md-6">
            <label class="col-sm-2 col-form-label" asp-for="RoleName">Name</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" asp-for="RoleName" placeholder="">
            </div>
        </div>
        <div class="form-group col-md-6">
            <label class="col-sm-2 col-form-label" asp-for="Description">Descriptiton</label>
            <div class="col-sm-8">
                <textarea class="form-control" asp-for="Description" rows="4" placeholder=""></textarea>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-sm-2 col-form-label">
                <input type="submit" value="Create" class="btn btn-success btn-tone m-r-5" />
            </div>
        </div>
    </form>
</div>

Areas/Admin/Views/AdminRole/Delete.cshtml
@model EcommerceWeb.Models.Role

@{
    ViewData["Title"] = "Delete Role";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminRole" asp-action="Index" class="breadcrumb-item">Manage role</a>
            <span class="breadcrumb-item active">Delete role</span>
        </nav>
    </div>
</div>

<div>
    <h3>Are you sure you want to delete this role ?</h3>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Role Info</h4>
            <div class="table-responsive">
                <table class="product-info-table m-t-20">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td class="text-dark font-weight-semibold">@Model.RoleId</td>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>@Model.RoleName</td>
                        </tr>
                        <tr>
                            <td>Descriptiton</td>
                            <td>@Model.Description</td>
                        </tr>
                    </tbody>
                </table> 
            </div>
        </div>
    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="RoleId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

Areas/Admin/Views/AdminRole/Details.cshtml
@model EcommerceWeb.Models.Role

@{
    ViewData["Title"] = "Role Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminRole" asp-action="Index" class="breadcrumb-item">Manage role</a>
            <span class="breadcrumb-item active">Role detail</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Role Info</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleId</td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td>@Model.RoleName</td>
                    </tr>
                    <tr>
                        <td>Descriptiton</td>
                        <td>@Model.Description</td>
                    </tr>
                </tbody>
            </table> 
        </div>
    </div>
</div>

Areas/Admin/Views/AdminRole/Edit.cshtml
@model EcommerceWeb.Models.Role

@{
    ViewData["Title"] = "Edit Role";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminRole" asp-action="Index" class="breadcrumb-item">Manage role</a>
            <span class="breadcrumb-item active">Edit role</span>
        </nav>
    </div>
</div>
<div>
    <h1>Edit role</h1>

    <form asp-action="Edit" asp-route-id="@Model.RoleId" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="RoleId">
        <div class="form-group col-md-6">
            <label class="col-sm-2 col-form-label" asp-for="RoleName">Name</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" asp-for="RoleName" placeholder="">
            </div>
        </div>
        <div class="form-group col-md-6">
            <label class="col-sm-2 col-form-label" asp-for="Description">Descriptiton</label>
            <div class="col-sm-8">
                <textarea class="form-control" asp-for="Description" rows="4" placeholder=""></textarea>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-sm-2 col-form-label">
                <input type="submit" value="Save" class="btn btn-success btn-tone m-r-5" />
            </div>
        </div>
    </form>
</div>

Areas/Admin/Views/AdminRole/Index.cshtml
@model IEnumerable<EcommerceWeb.Models.Role>

@{
    ViewData["Title"] = "Manage Role";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Manage role</span>
        </nav>
    </div>
</div>

<div>
    <h1>Manage Role</h1>

    <p>
        <a class="btn btn-primary btn-tone m-r-5" asp-action="Create">Create </a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                    <tr>
                        <th scope="row">@item.RoleId</th>
                        <td>@item.RoleName</td>
                        <td>@item.Description</td>
                        <td>
                            <a class="btn btn-success btn-tone m-r-5" asp-action="Edit" asp-route-id="@item.RoleId">Edit</a> |
                            <a class="btn btn-secondary btn-tone m-r-5" asp-action="Details" asp-route-id="@item.RoleId">Detail</a> |
                            <a class="btn btn-danger btn-tone m-r-5" asp-action="Delete" asp-route-id="@item.RoleId">Delete</a>
                        </td>
                    </tr>
            }
        </tbody>
    </table>

</div>